name: reminderx_mobile
description: "A reminder to renew particulars"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.2
  flutter_carousel_widget: ^2.2.0
  intl: ^0.19.0
  isar:
    hosted:
      name: isar
      url: https://pub.isar-community.dev/
    version: ^3.0.0

  isar_flutter_libs:
    hosted:
      name: isar_flutter_libs
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  table_calendar: ^3.0.9
  file_picker: ^10.1.9
  url_launcher: ^6.2.2
  pdfrx: ^1.0.0
  path: ^1.9.1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  isar_generator:
    hosted:
      name: isar_generator
      url: https://pub.isar-community.dev/
    version: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/login_background.png
    - assets/images/signup_background.png
  fonts:
    - family: InknutAntiqua
      fonts:
        - asset: assets/fonts/InknutAntiqua-Regular.ttf
    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Regular.ttf

 
